### ISSUE TITLE
Ways to indicate "In Progress" within `imgpkg`

### ISSUE THREAD

**Issue by pivotaljohn** [carvel-dev/imgpkg#163]
**In the beginning**,
- there was an intent to improve the experience of the user waiting for images to copy (#132)
- that idea spawned a spinner (#133)
- ... which didn't seem entirely "right." because of that, it was pulled off into a separate PR (#134)
- which sat for a while, grew stale and was closed.

_This_ discussion is about circling back to that original intent and seeing what we learned from the above-described attempt so that we could realize the intent in a better way.

That discussion started elsewhere like this:

@cppforlife said
> we briefly started talking about spinners and what exactly it helps with (and doesnt). discussion wasnt continued im guessing due to other priorities so i've closed it for now. we can start a discussion again if ppl have time.
> ... from what i recall we never got to an agreement regrading this UX paradigm in carvel (spinners arent anywhere in carvel) ... blockage here is on UX.

@DennisDenuto noted and asked:
> Ok... so the original problem (users don't know what is happening in imgpkg because they see a blank screen for a moment) is deemed as a valid problem to solve... but it was the decision to use a spinner to solve that problem that is the issue.
>
> What is the UX paradigm in carvel? Was the option to introduce 'spinners' into this paradigm discussed? or tackled another way, what is the carvel way to show that the program is 'loading' / how do we prompt the user to just chill for a moment?

... aaaaaaannnd... ACTION! 🎬

**Comment by DennisDenuto** [comment]
Nice. Well TIL that there is a notion of a UX paradigm in carvel. I'm gonna take it for granted that this is something we want to strive towards.

That paradigm isn't known to me. I'm hoping have some definition on what that actually is. With that shared definition it should be hopefully easier to see whether a 'spinner' fits well or doesn't, and what might be a better alternative.  

Here's a stab in the dark: There is an ambition to have the carvel tools have a more 'uniform' way of displaying information to users. As well as having a 'uniform' way of running / configuring the tools. Although for this convo I think sticking to displaying information makes sense.

Different information that our tools display are (not limited to):
- output
- debugging
-- internal state 
-- progress 
- informational
- errors

ytt:
```
- output: YAML
- debugging
-- internal state: shows a graph-like structure of nodes
-- progress: n/a because ytt is bound by CPU, memory so output typically happens quickly. Validated with large code bases.
- informational: detection of potentially incorrect usage of command. i.e. flags such as experimental schema
- errors: Structured assertion-like error, "expected vs actual" pointing the user to the problematic yaml file. 
```

imgpkg:
```
- output: Succeeded/Failed with image/bundle shas
- debugging
-- internal state: line item description
-- progress: We have a progress bar for when images are uploaded.  but in the case a pull takes time we display nothing.
- informational: detection of potentially incorrect usage of command. i.e. flags such as --non-distributable
- errors: A contextual error with the underlying error revealed too.
```

I haven't added the other tools like kapp or kbld yet, because i'm already seeing differences in the UX. Which I think reflect the difference in structures of information between the two tools. That difference in structure will lead to a different tailored UX.

**Comment by joaopapereira** [comment]
Not sure if we should be comparing the output of a tool like `ytt` and `imgpkg`. These 2 tools serve a different purpose and the displayed information on the screen hardly would be comparable.

As a example `ytt` is meant to print to standard output the result of computation that can afterwards be piped into a different tool, like `kbld` or `kapp`. While `imgpkg` output is meant for the Humans to read directly, and not consumable but a different tool. `imgpkg` is a particular case inside the carvel suite because it cannot be part of a pipeline of commands and need to always be used in a standalone manner, so if a particular UX element would make the UX of our users better we should not shy away from it just because it is not in other tools of the suite.

This being said I believe that argument wise we should try to be as consistent as we can. An example would be all tools should have some sort of debugging capabilities and they all should use the same command-line argument.

**Comment by joaopapereira** [comment]
I feel like this discussion has grown stale. Do we still believe it makes sense to keep this issue around?
@pivotaljohn @DennisDenuto @cppforlife

**Comment by joaopapereira** [comment]
As discussed today I am going to close this issue. In the future, we can reopen it if we think it is something that we want to improve the UX of `imgpkg`.
