### ISSUE TITLE
Allow specifying the number of retries

### ISSUE THREAD

**Issue by voor** [carvel-dev/imgpkg#231]
I am trying to do the unachievable, which is download gigabytes of data through an enterprise proxy server.  It's failing, a lot.  I've tried changing the concurrency, and that seems to help, but things are still failing.  I know if I keep trying it'll eventually work, and rather than creating a bash script to just forever loop this, I'd like to pass something into imgpkg.

Possibly add an option like `--num-retries=XX` or another logical flow that would allow me to `--just-go-until-it-works` might help this problem.

Note:
Slack conversation: https://kubernetes.slack.com/archives/CH8KCCKA5/p1630527017057500

---

Related work summary:

- [x] https://github.com/google/go-containerregistry/issues/1114
- [x] https://github.com/google/go-containerregistry/pull/1122

**Comment by DennisDenuto** [comment]
Related to: https://github.com/google/go-containerregistry/issues/1114

**Comment by pivotaljohn** [comment]
Triage:
- split out work to change the imgpkg default to 15.
- @DennisDenuto and @cppforlife to huddle to decide whether this is configurable to the imgpkg user.

**Comment by vrabbi** [comment]
this would be great to have. im trying to create a VERY large imgpkg bundle for an airgapped scenario with 942 images in it. this is a package repository. the file size is 67GB when copied to TAR. eventually after about 1000 layers there is usually some temporary network issue which unfortunately isnt fixed in time for the current retry number to take continue on successfully.
copying to tar is taking ~3+ hours and has yet to finish because of issues like this. having the retry count configurable would make this much smoother

**Comment by aaronshurley** [comment]
Just as a reference, the gcr work was in the last release: https://github.com/google/go-containerregistry/releases/tag/v0.7.0

**Comment by joaopapereira** [comment]
The PR was merged and will be released in version 0.24.0

**Comment by joaopapereira** [comment]
Released on version 0.24.0
