### ISSUE TITLE
imgpkg tag list adds tab character after results

### ISSUE THREAD

**Issue by voor** [carvel-dev/imgpkg#264]
**What steps did you take:**
```
imgpkg tag list -i hello-world
```

**What happened:**
```
Tags

Name  
latest  
linux  
nanoserver  
nanoserver-1709  
nanoserver-1803  
nanoserver-1809  
nanoserver-ltsc2022  
nanoserver-sac2016  
nanoserver1709  

9 tags

Succeeded
```

**What did you expect:**
No tab characters after results.

**Anything else you would like to add:**
This would probably be the motivation for a `--filter` command or similar to allow me to avoid piping this to grep.

**Environment:**

- imgpkg version (use `imgpkg --version`): `0.17.0`
- Docker registry used (e.g. `Docker HUB`): `hello-world`
- OS (e.g. from `/etc/os-release`): Linux

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Hey @voor 

Thanks for creating this bug!

Are you able to elaborate on the pain / issue with the format of the output (i'm assuming its causing some scripting difficulties?)

Here's a run-down with imgpkg's logic around output:

When you run the list tags command, and the output is attached to a tty then the output *should* print out white spaces (not tabs) at the end of the string value in that column. 

Are you able to confirm that the output does *indeed* have tabs and not white spaces?

I *would* expect tabs to appear if you run that command without attaching to a tty. e.g. if you redirect to a file. Tabs are used in that case to help work nicer with scripting tools (like cut)

Let me know if the above isn't the case, or if tabs is actually making it harder to use scripting tools! :-)

**Comment by voor** [comment]
Hi @DennisDenuto it was causing the following script to fail very annoyingly (since it was getting the space):
```
imgpkg pull -o tkr-bom -i "projects.registry.vmware.com/tkg/tkr-bom:$(imgpkg tag list -i projects.registry.vmware.com/tkg/tkr-bom | sort --version-sort -r | head -n1)"
```

Although I realize now everything would have been fine and proceeded as normal if I had just removed the `"` from the call:

```
imgpkg pull -o tkr-bom -i projects.registry.vmware.com/tkg/tkr-bom:$(imgpkg tag list -i projects.registry.vmware.com/tkg/tkr-bom | sort --version-sort -r | head -n1)
```

**Comment by DennisDenuto** [comment]
Thanks for sharing that scripting snippet

I'm kinda inclined to close this issue (let me know if you feel strongly otherwise). With the rationale being, when printing a table format, we should leave the delimiter as spaces between columns (the `tag` command only has a single column, but if there were multiple columns, consumers should expect spaces as the delim between the columns). I'm also hoping (although it's kinda a stretch) it will make devs consider the output having multiple columns in the future. In your example, I would encourage you to parse the output by the space delim, and select the first column (to make it a lil more future proof)

FWIW `imgpkg` also supports returning the output in json format (via the `--json` flag) - the string values in that output doesn't contain spaces (letting you wrap the bash expression around double quotes). You could use `jq` to sort / map the values into the correct format.

> This would probably be the motivation for a --filter command

Yeah! All ideas are welcome! I'd ask if you can please create a separate feature request issue so that we can better understand the ask and use case. And also helps us manage our backlog of work too :-)

**Comment by voor** [comment]
Sounds good, the `--json` output might be a more robust solution as well.
