### ISSUE TITLE
Using imgpkg for populating container runtime image cache

### ISSUE THREAD

**Issue by voor** [carvel-dev/imgpkg#277]
**Describe the problem/challenge you have**
We often times run our nodes in environments where they initially do not have a container registry. We take advantage of the fact that the Kubernetes cluster temporarily disabled `AlwaysPullImages` and permits `IfNotPresent`.  This allows us to immaculately conceive a Harbor cluster that is actually hosted with the same Harbor cluster's images, so `mycoolharbor.example.com` is actually running a cluster filled with `mycoolharbor.example.com` images for everything.  While this sounds crazy, it has worked immaculately for a good long while.  Things started to get slightly wonky when we moved our underlying CNI over to imgpkg.  Since the containers for the CNI are now being relocated to another tag and referenced directly to sha256 images, we lose access to the pulled and tagged images.  What _was_:
```
# I exist and am cached
mycoolharbor.example.com/tkg/antrea/antrea-debian:v0.11.3_vmware.2 
```
Now suddenly becomes:
```
# I do not exist, I didn't know this was what I'd expect
mycoolharbor.example.com/tkg/packages/core/antrea@sha256:8afde47bac81a8dc51050568a60f4fb2f7b17ac20f7f3372ca907710d8d6bc88
```
Except what was cached on our node image is still just a reference to `mycoolharbor.example.com/tkg/antrea/antrea-debian:v0.11.3_vmware.2`.  It's the **exact same layers** but since we don't have a registry yet, there's no way to perform this resolution.

_Note: Yes, I realize imgpkg doesn't do caching either right now, so this is skipping the fact that kapp-controller will have failed prior to this since imgpkg bundles could never be pulled in the first place._

**Describe the solution you'd like**
_Assuming we eventually figure out imgpkg caching_, some solution where I could do:
```
imgpkg copy -b dkalinin/app1-bundle --to-repo internal-registry/app1-bundle --local
```
And the `--local` just does something like `ctr pull` and `ctr tag` to everything from the imgpkg bundle would be the solution that would allow this to mimic a imgpkg copy with an expectation that the registry will exist later at this location.

**Anything else you would like to add:**
Since the node is impersonating something that will eventually sync up to sha256 layers, just originating from somewhere else, the recreation of the tags is not necessary, just trying to recreate that idea that `mycoolharbor.example.com/tkg/antrea/` gets rewritten to `mycoolharbor.example.com/tkg/packages/core/antrea`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Hey @voor Thanks for the detailed issue

> there's no way to perform this resolution

I'm not too familiar with `ctr` but groking their code, they seem to have an `images` command that might be able to print out the digest for the cached image in question. https://github.com/containerd/containerd/blob/main/cmd/ctr/commands/images/images.go#L94

This might also be a good idea to ensure you are actually running the exact image since tags are mutable and could be pointing to stale / incorrect image digest.

On that note: what happens when you pull by digest `mycoolharbor.example.com/tkg/packages/core/antrea@sha256:8afde47bac81a8dc51050568a60f4fb2f7b17ac20f7f3372ca907710d8d6bc88` does it fail? and if so what is the error message you are seeing?

> And the --local just does something like ctr pull and ctr tag

My current thinking is: loading an image into a container runtime (in this case containerd) slightly blurs the lines of responsibility of imgpkg. Which I think should be about creating and distributing bundles across registries. Leaving the running of images to another tool. Also I think each container runtime would require its own separate library to perform this operation. So theres an engineering overhead i'm factoring in too.

I wonder, do you think this workflow would be an improvement:

```
imgpkg copy -b dkalinin/app1-bundle --to-oci-tar /local-disk/app1.tar
ctr import --base-name internal-registry/app1-bundle /local-disk/app1.tar  
```

This change introduces a new flag `--to-oci-tar` that exports a tarball in an OCI compatible format allowing container runtimes to load it in. It still requires ctr to import the image. but doesn't require any network access.

**Comment by voor** [comment]
So we went back to the whiteboard and dove into this a bit more and realize our use case is slightly different.

We successfully copy over a imgpkg bundle from somewhere else, and in the process those containers all change where they are, but that's clearly outlined in the imgpkg lock file, for example:

```
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: antrea/antrea-ubuntu:v0.13.3
  image: coolharbor.example.com/tkg/packages/core/antrea@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102
kind: ImagesLock
```

We can then iterate through this file, along with others, pulling the container from there in an environment where it *does* exist:

```
ctr i pull coolharbor.example.com/tkg/packages/core/antrea@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b12
```

If there were more images, it'd do more commands.

The trick was we're pulling from the POST copied environment, instead of trying to grok our heads around the PRE copied environment.  This could be mimicked with a temporary repository stood up at `uncoolharbor.example.com`

```
ctr i pull uncoolharbor.example.com/tkg/packages/core/antrea@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b12
ctr i tag uncoolharbor.example.com/tkg/packages/core/antrea@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b12 coolharbor.example.com/tkg/packages/core/antrea@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b12
```

So the big difference is now instead of trying to guess imgpkg's new copy location, we're just doing it, pulling the resulting imgpkg bundle, and looping through it.

I think where better value would be achieved is if there was some way to crawl a higher order construct (like Package Repository) and get a "super list" of all the included bundles, but since right now we have a countable number of things super important to cache on a node (and kubeadm pull handles most of them already), this issue seems less important now.
