### ISSUE TITLE
`imgpkg copy --to-tar` should detect already existing .tar (performance improvement)

### ISSUE THREAD

**Issue by Excpt0r** [carvel-dev/imgpkg#330]
**Describe the problem/challenge you have**
I'm using the [tkg doc](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-mgmt-clusters-image-copy-airgapped.html) for airgapped installation, which uses a script with many calls to imgpkg to download a complete tanzu release.
There are scenarios where it would save time and bandwidth, when imgpkg would detect already locally existing .tar files:
- when a previous tanzu release download failed in the middle, or the download script runs multiple times as part of multiple cluster installations.
- when only parts between two tanzu releases changed, only the changed/new parts need to be downloaded

The current behaviour is, that imgpkg downloads all layers and (over)writes all .tar files new.

**Describe the solution you'd like**
Before writing a .tar file, check if it exists locally.
If the .tar exists, compare every image layer included in the .tar with the remote sha256 checksum.
Only if any sha256 is wrong or a layer is missing - download and write the .tar again completely.
Also check if any layers are included in the .tar that are not there remotely.

Detecting and keeping some layers and only add/replace others where needed would even better,
but probably not worth the added complexity.
If I download 60 images and want to resume after 30 images, I don't care if I start at 50% or 51% image, just not at 0%.

**Anything else you would like to add:**
Maybe have a look how others solve this task (i.e. "oc image mirror").
I don't know the implementation, but having a file containing all image URLs provided to a single imgpkg call
could be faster in terms of connection/auth re-use.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
This looks like an interesting behavior that can be used in multiple situations.

Some implications that I see here:
- If we make this the default behavior people could point the copy to a random tar, so `imgpkg` should fail if the tar exists and is not already in the format expected
- we currently do concurrent write of the tar we need to make sure that we remove the entries of the tar that were not completely written (not sure how complicated this would be) (Images that were not completely downloaded)
- To prevent any problem this feature should not be implemented before we define #282 since people can pick up a half copied tar and try to copy it to a repository. This will fail until that particular feature is implemented.


Some considerations that we should think about before implementing this story:
1. Should this be the default behavior or should it be a flag?
2. When we retry to copy to tar should we provide a flag `--continue` or something similar so that `imgpkg` knows something is already present?
3. Can we still do concurrent writes on a tar file even if we implement this behavior?


For now I am going to accept this story, but we should do some investigation before we start implementing it and even discuss some of the prior questions

**Comment by benmoss** [comment]
This seems relevant, though not using GGCR https://github.com/moby/moby/pull/18353

**Comment by joaopapereira** [comment]
Fixed by #418 will be out in the next release
