### ISSUE TITLE
imgpkg copy failed with tar file option

### ISSUE THREAD

**Issue by snehalbiche** [carvel-dev/imgpkg#374]
facing issue while copying image from tar, provided CA certificate path and also tried providing ca.crt file content but it results with same error. need help to understand why imgpkg is failing to copy? 

linu@tkgbootstrap:~$ echo $TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE
/home/linu/ca.crt

linu@tkgbootstrap:~$ imgpkg copy --tar /home/linu/image-tar/tkr-bom-v1.17.16_vmware.2-tkg.1.tar --to-repo tkgbootstrap.tanzu.lab/tkg/tkr-bom --registry-ca-cert-path base64-ca.crt 
imgpkg: Error: Creating registry HTTP transport:
  Adding CA certificates from 'base64-ca.crt': failed

**Comment by joaopapereira** [comment]
Hello,
Thanks for opening this issue.
This is quite a cryptic message, but unfortunately, the library does not provide a lot of extra information.

From looking at the Golang standard libraries the possible problems that can happen are:
1. Decoding the certificates from the file does not produce any certificates
2. The file does not contain certificates in the expected form, [example](http://ospkibook.sourceforge.net/docs/OSPKI-2.4.7/OSPKI-html/sample-ca-cert.htm)
3. Any particular issue with a certificate (this one is the hardest because multiple things can be the cause, but basically it is not a valid certificate)


In order to start debugging the problem you can try the following:
- Is the .crt file a valid PEM file
- Execute `openssl verify base64-ca.crt` 
- If the file is a ca-bundle you can execute `openssl verify -untrusted ca-bundle base64-ca.crt`

If using openssl verifies the PEM file, maybe you can join us in `#carvel` channel in the kubernetes Slack and we can try to do a live session (zoom) and try to better debug the issue.

For a better error message in imgpkg not sure if we can do much because the standard libraries in this situation do not provide any information that is helpful. 

Hope that this information helps
