### ISSUE TITLE
[internal] ImageSet.Export isnt strictly checking digest refs

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#42]
we no longer use NewDigest to parse refs here: https://github.com/vmware-tanzu/carvel-imgpkg/blob/develop/pkg/imgpkg/cmd/image_set.go#L41-L46 (commend is out of date now). but unless something changed we should still be parsing refs as digests. if we are trying to transfer over tags then i would imagine it should be an additional field and not muddy up ref itself.

**Comment by cari-lynn** [comment]
This change happened when we started preserving image tags throughout copying.

Looking over the code, it seems we now parse the ref generically. We parse using NewDigest if it is a digest reference, otherwise we parse it as a tag.
https://github.com/vmware-tanzu/carvel-imgpkg/blob/d4982fa6c0aa2ef64e4151e39b91785e437610bf/vendor/github.com/google/go-containerregistry/pkg/name/ref.go#L39-L46

We should look into why we no longer use `regname.StrictValidation` when using NewDigest.

> we should still be parsing refs as digests

It looks like we are still doing this. Am I missing something here?

> if we are trying to transfer over tags then i would imagine it should be an additional field and not muddy up ref itself

Can you explain what you mean by "transfer over tags here" and your vision for "not muddy up ref itself"?

**Comment by cppforlife** [comment]
the intent of ImageSet is to work with concrete images (== digest refs); however, for some images we also want to throw in additional metadata like a tag. that meaning was changed by having ImageSet do tag resolution. this now means that i could call ImageSet.Export twice and get different results because tag may change.

**Comment by cari-lynn** [comment]
I agree, we want to have ImageSet use digest references, rather than accept a digest or a tag. Doing this will ensure that the image references are in digest form and a ref always maps to the same image.

Like you said, we can refactor ImageSet to parse image urls with `NewDigest` rather than `ParseReference` as it is now to address this.

Still not sure I 100% understand the idea that tags should be an additional field but it would be something to think about when someone picks this up and looks closer at the code.

**Comment by cppforlife** [comment]
fixed as part of https://github.com/vmware-tanzu/carvel-imgpkg/pull/48

**Comment by gcheadle-vmware** [comment]
Closing issue with release of version 0.3.0
