### ISSUE TITLE
imgpkg tag list without the .imgpkg tags

### ISSUE THREAD

**Issue by alexbarbato** [carvel-dev/imgpkg#459]
**Describe the problem/challenge you have**
Currently when one is to try and do an imgpkg list they can get a very large response of tags (sometimes thousands). This results in a quite slow loading experience, particularly when one is trying to just see versions that are relevant to copy.

**Describe the solution you'd like**
At a minimum it'd be nice to only get "latest" by some time period or some version there in.
Another option would be to remove the ".imgpkg" results as I don't know that they are human useful.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
Hey @alexbarbato 
This is something that I thought about before, especially when you have repositories containing multiple versions of PackageRepositories and such.
Nevertheless, I do not think we can convert this into a default behavior because there might be people already relying on this functionality to get images and such.

> At a minimum it'd be nice to only get "latest" by some time period or some version there in.

I am not 100% sure we can do this since we remove all the concepts of dates on the bundles to ensure that they are repeatable, and tags do not have a date associated with them.


From what I have seen I believe we could create a flag similar to `--only-valid-semver` or `--exclude-internal` that would remove the `*.imgpkg` tags.

What do yll think about these options?

**Comment by alexbarbato** [comment]
I'd be all for either option!

(with the added desire that this isn't just a client side filtration mechanism as I imagine that wouldn't necessarily increase the speed at all - but I suppose we'd need to test that)

**Comment by joaopapereira** [comment]
Unfortunately, there is no endpoint to search for tags in a repo the only option is to list all of the tags and afterward filter them locally.


Do you have any preference for the flag behavior?

**Comment by cppforlife** [comment]
my 2c: --imgpkg-internal-tags=true/false (by default perhaps we should set it to false -- change in default behaviour, since most folks dont care about *.imgpkg tags)

**Comment by joaopapereira** [comment]
We are going to accept this issue, with the caveat that we will have to get all the tags and that the filtering will happen on the client side.

> my 2c: --imgpkg-internal-tags=true/false (by default perhaps we should set it to false -- change in default behaviour, since most folks dont care about *.imgpkg tags)

No objections, I think we can break compatibility in this one case since it would make more sense to do not to show all the tags in a repository mainly if the repository contains multiple bundles on them. Also ok with the naming of the flag

**Comment by joaopapereira** [comment]
Marking this issue as a good first issue. If someone wants to pick it up feel free, just let us know. Also if you need some help with the implementation let us know.
Not sure when the maintainers will have the bandwidth to implement this, so I made it a longterm priority as well.

**Comment by alexbarbato** [comment]
gave it an initial pass and all feedback welcome :D

**Comment by joaopapereira** [comment]
Fixed on version [v0.35.0](https://github.com/carvel-dev/imgpkg/releases/tag/v0.35.0)
