### ISSUE TITLE
Facilitate a way to correlate requests made from imgpkg copy with an unique id to club them to one logical bucket

### ISSUE THREAD

**Issue by jhasu** [carvel-dev/imgpkg#545]
**Describe the problem/challenge you have**
Currently imgpkg in its requests don't have an unique id which can logically tie all the independent manifest and blob endpoint requests for a download session made into one logical bucket. This correlation at times is desired to correlate the requests  to one download session.

**Describe the solution you'd like**
A unique identifier can be added to the header information to imgpkg client request which will be present in all the request made for one download session initiated by a user.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
Hey @jhasu 
It could be an interesting feature that could help any registry to track what each user is retrieving or pushing into a registry at one specific time.

The request here sounds like a new header that we would include in each request to the registry that would be unique per execution of imgpkg. Not sure if there is a good HTTP header that we could piggyback on if not, maybe we can create a header called `imgpkg-session-id` or something similar that would contain an SHA or an OOID for each execution of imgpkg.

Do yll have any suggestions on the Header name?

Going to mark this accepted since it looks like a good feature to have.

**Comment by jhasu** [comment]
Thank you @joaopapereira. 
I think "imgpkg-session-id" sounds to be an appropriate header name for this.
