### ISSUE TITLE
Air gapped workflow doesn't work

### ISSUE THREAD

**Issue by cari-lynn** [carvel-dev/imgpkg#80]
**What steps did you take:**
@DennisDenuto and I ran `imgpkg` in an internetless environment. We copied a tar file to a repository:

0) turn on external access to the internet 
1) `./imgpkg copy -i ubuntu --to-tar ubuntu.tar`
2) turn off external access to the internet (but keep access to the internal registry)
3)` ./imgpkg-linux-amd64 copy --tar ./ubuntu.tar --to-repo air.gapped.registry/image`

**What happened:**
imgpkg tries to get the image in the tar from the original registry 

```
copy | importing 1 images...
copy | importing index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e -> 172.19.0.2/rept/image@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e...
copy | imported 0 images
Error: Importing image index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e: Importing image as 172.19.0.2/rept/image@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e: Writing image: Retried 5 times: Get "https://172.19.0.2/v2/": dial tcp 172.19.0.2:443: connect: connection refused; Get "http://172.19.0.2/v2/": dial tcp 172.19.0.2:80: connect: connection refused
```

**What did you expect:**
I expect that `imgpkg` copies the image from the tar file, not from `index.docker.io/library/ubuntu`.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- imgpkg version (use `imgpkg --version`): imgpkg version 0.4.0
- Docker registry used (e.g. `Docker HUB`): docker
- OS (e.g. from `/etc/os-release`): linux

**Comment by joaopapereira** [comment]
I replicated the issue, but I am not sure that the "What happened" is accurate. If you look at the error message it says `172.19.0.2:80: connect: connection refused` and that IP address is a local IP.
To reproduce the problem in my case I did create a container in my Mac started a registry inside that container, and did:
```
imgpkg  copy -i ubuntu --to-tar ubuntu.tar
copy | exporting 1 images...
copy | will export index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e
copy | exported 1 images
copy | writing layers...
copy | done: file 'manifest.json' (24.85µs)
copy | done: file 'sha256-f611acd52c6cad803b06b5ba932e4aabd0f2d0d5a4d050c81de2832fcb781274.tar.gz' (77.614µs)
copy | done: file 'sha256-db98fc6f11f08950985a203e07755c3262c680d00084f601e7304b768c83b3b1.tar.gz' (42.448µs)
copy | done: file 'sha256-83ee3a23efb7c75849515a6d46551c608b255d8402a4d3753752b88e0dc188fa.tar.gz' (1.179138506s)
Succeeded
```
Turned off the internet run
```
imgpkg copy --tar ./ubuntu.tar --to-repo localhost:5050/ubuntu-1
copy | importing 1 images...
copy | importing index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e -> localhost:5050/ubuntu-1@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e...
copy | imported 0 images
Error: Importing image index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e: Importing image as localhost:5050/ubuntu-1@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e: Writing image: Retried 5 times: Get "https://localhost:5050/v2/": dial tcp 127.0.0.1:5050: connect: connection refused; Get "http://localhost:5050/v2/": dial tcp 127.0.0.1:5050: connect: connection refused
```

When I turned on the internet I run
```
imgpkg copy --tar ./ubuntu.tar --to-repo localhost:5050/ubuntu-1
copy | importing 1 images...
copy | importing index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e -> localhost:5050/ubuntu-1@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e...
copy | imported 0 images
Error: Importing image index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e: Importing image as localhost:5050/ubuntu-1@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e: Writing image: Retried 5 times: Get "https://localhost:5050/v2/": dial tcp 127.0.0.1:5050: connect: connection refused; Get "http://localhost:5050/v2/": dial tcp 127.0.0.1:5050: connect: connection refused
```

I did get exactly the same error and the IP address is for my local registry running in my docker container.

What the message is trying to convey is that it is copying the image "referenced by" `index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e` to `localhost:5050/ubuntu-1@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e` and not that it is copying the image "from" `index.docker.io/library/ubuntu@sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e`.

Given what I saw in my reproduction, I assume that the problem happens when `imgpkg` tried to talk with my local registry and not because it is trying to connect to Docker hub.

I only saw this problem in this docker in docker environment and have not tried to reproduce it in a VM or Real Linux machine.

When I run the same scenario above on my Mac it worked, so the assumption is that this is a Linux-specific problem.

---

Notes:
Steps to do my setup:
On the Mac
```
$ docker run -it -v /var/run/docker.sock:/var/run/docker.sock ubuntu:20.04 bash
```
Inside the container
```
$ apt-get update
$ apt-get install docker.io wget -y
$ docker run -d -p 5050:5000 --restart always --name registry registry:2
$ wget https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v0.4.0/imgpkg-linux-amd64
$ chmod u+x imgpkg-linux-amd64
$ mv imgpkg-linux-amd64 imgpkg
$ ./imgpkg  copy -i ubuntu --to-tar ubuntu.tar
```
---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.

**Comment by DennisDenuto** [comment]
@joaopapereira @cari-lynn 
I have been *unable* to reproduce either of the above issues on my machine.

Here are the exact steps I used:


```
cd ~/workspace/imgpkg
git checkout develop
git show 
> 113d738ad43d4acb9a5c8d7012708884a631ca95
./hack/build-binaries.sh

# internet available
docker run -d -e REGISTRY_VALIDATION_MANIFESTS_URLS_ALLOW='- ^https?://' --restart always --name registry registry:2
export REGISTRY_IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry)"
docker run -e IP=$REGISTRY_IP -t -i -v $PWD:/tmp/imgpkg golang /bin/bash
> cd /tmp/imgpkg
> curl -v google.com # this works.... we have internet!
> ./imgpkg-linux-amd64 copy -i ubuntu --to-tar ubuntu.tar
> ./imgpkg-linux-amd64 copy --tar ubuntu.tar --to-repo "$IP:5000/some/repo"

Result:
Succeeded

# now for the airgapped test
docker kill registry
docker container prune

docker network create --driver bridge --internal airgapped

docker run --network=airgapped -d -e REGISTRY_VALIDATION_MANIFESTS_URLS_ALLOW='- ^https?://' --restart always --name registry registry:2

export REGISTRY_IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry)"
docker run -e IP=$REGISTRY_IP -t -i --network airgapped -v $PWD:/tmp/imgpkg golang /bin/bash
> curl -v google.com # this fails.... good because there is no internet on purpose!
> cd /tmp/imgpkg
> ./imgpkg-linux-amd64 copy --tar ubuntu.tar --to-repo "$IP:5000/some/repo"

Result:
Succeeded

```

**Comment by DennisDenuto** [comment]
@joaopapereira and I paired on this. We feel confident that the airgapped workflow is *not* broken.

specifically, when copying from a tarball to a repo, in an internetless environment, the images *do* come from the tarball. No requests are made to the 'originating' registry.

As for Joao's above comment, the issue there was that the incorrect ip address for the registry was used. i.e. `localhost:5050` should have been `<IP address of registry container>:5000`
